conversation:
  all-language:
  - English
  - Turkish
  - Spanish
  current-dialect:
    index: 0
    name: eng
  dialects:
    english:
      index: 0
      name: eng
    spanish:
      index: 2
      name: esp
    turkish:
      index: 1
      name: tr
  language: esp
  zone: 10
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9090
